"""Writer for frb_evidence_matrix.csv (host/environment/population rows).

Deterministic; no randomness. Run:
    python build_matrix.py <output_csv_path>
"""
import csv
import sys

COLUMNS = [
    "evidence_id", "observation", "source_name", "citation", "locator",
    "hypothesis", "effect", "strength", "applies_to", "confidence_note",
    "unresolved_ambiguity",
]

ROWS = [
    dict(
        evidence_id="EV-H01",
        observation="Host of FRB 121102 is a low-metallicity, low-mass dwarf star-forming galaxy at z=0.19273, resembling hosts of superluminous supernovae and long GRBs.",
        source_name="FRB 20121102A",
        citation="Tendulkar et al. 2017, ApJL",
        locator="abstract; host redshift and SED/metallicity section",
        hypothesis="magnetar-core-collapse",
        effect="supports",
        strength="strong",
        applies_to="single-source",
        confidence_note="Localization and host association are secure; the SLSN/LGRB-host analogy is the authors' interpretation, not a measurement.",
        unresolved_ambiguity="One object. Later localizations show dwarf hosts are the minority, so this cannot be generalized to the population.",
    ),
    dict(
        evidence_id="EV-H02",
        observation="Compact, luminous persistent radio source (PRS) spatially coincident with FRB 121102 to within the localization precision (sub-arcsecond, VLA; later milliarcsecond-scale with VLBI).",
        source_name="FRB 20121102A",
        citation="Chatterjee et al. 2017, Nature",
        locator="abstract; VLA localization and persistent-source photometry",
        hypothesis="magnetar-core-collapse (young magnetar in dense nebula)",
        effect="supports",
        strength="strong",
        applies_to="single-source",
        confidence_note="Existence and compactness of the PRS are robust; its physical nature is not established by the detection itself.",
        unresolved_ambiguity="PRS could be a magnetar wind nebula, a young supernova remnant, or an accretion-powered source (low-luminosity AGN / X-ray binary analogue). Degenerate.",
    ),
    dict(
        evidence_id="EV-H03",
        observation="FRB 121102 bursts are coincident with a bright star-forming knot (HII region) within the dwarf host rather than with the host nucleus.",
        source_name="FRB 20121102A",
        citation="Bassa et al. 2017, ApJL",
        locator="abstract; HST/optical imaging of the star-forming region",
        hypothesis="magnetar-core-collapse",
        effect="supports",
        strength="moderate",
        applies_to="single-source",
        confidence_note="Association with the star-forming knot is strong; the precise offset in parsecs is not quoted here because I am not confident of the exact figure.",
        unresolved_ambiguity="Coincidence with a star-forming region does not by itself establish a young age; the star-forming knot dominates the host light, so chance alignment is not negligible.",
    ),
    dict(
        evidence_id="EV-H04",
        observation="FRB 20190520B is a second repeater with a compact persistent radio source in a dwarf star-forming host, i.e. the 121102-like configuration is not unique.",
        source_name="FRB 20190520B",
        citation="Niu et al. 2022, Nature",
        locator="abstract; host identification and persistent-source sections",
        hypothesis="magnetar-core-collapse (young magnetar in dense nebula)",
        effect="supports",
        strength="moderate",
        applies_to="single-source",
        confidence_note="Detection secure. Whether the PRS is powered the same way as in FRB 121102 is assumed, not shown.",
        unresolved_ambiguity="Both PRS systems are repeaters with extreme dispersion and rotation measures; unclear whether this is a separate sub-class or an early evolutionary stage common to all sources.",
    ),
    dict(
        evidence_id="EV-H05",
        observation="FRB 20180916B localized with milliarcsecond precision to a star-forming region in the outskirts of a nearby, massive spiral galaxy at z=0.0337.",
        source_name="FRB 20180916B",
        citation="Marcote et al. 2020, Nature",
        locator="abstract; EVN localization and host identification",
        hypothesis="magnetar-core-collapse",
        effect="supports",
        strength="moderate",
        applies_to="single-source",
        confidence_note="Localization is secure. Support is weaker than for FRB 121102 because a normal spiral host is not a distinctive prediction of this channel.",
        unresolved_ambiguity="A massive spiral host is compatible with essentially every progenitor hypothesis; the host type alone carries little discriminating power.",
    ),
    dict(
        evidence_id="EV-H06",
        observation="FRB 20180916B is offset by roughly a few hundred parsecs from the nearest bright star-forming knot, with no coincident young stellar population at the burst position.",
        source_name="FRB 20180916B",
        citation="Tendulkar et al. 2021, ApJL (60 pc environment of FRB 20180916B)",
        locator="abstract; offset from nearest star-forming knot",
        hypothesis="magnetar-core-collapse with a very young (<~ few hundred year) magnetar",
        effect="challenges",
        strength="moderate",
        applies_to="single-source",
        confidence_note="I am confident of the qualitative offset result but NOT of the exact parsec value; verify the number against the source before quoting it.",
        unresolved_ambiguity="Offset can be explained by a natal kick plus an age of >~1e5 yr, by a runaway progenitor, or by an older formation channel; these are not separated by the imaging.",
    ),
    dict(
        evidence_id="EV-H07",
        observation="FRB 20200120E localized to a globular cluster associated with M81, i.e. to an old, metal-poor, low-star-formation stellar environment.",
        source_name="FRB 20200120E",
        citation="Kirsten et al. 2022, Nature",
        locator="abstract; VLBI localization and globular cluster identification",
        hypothesis="magnetar-core-collapse",
        effect="challenges",
        strength="strong",
        applies_to="single-source",
        confidence_note="Localization to the globular cluster is secure and the cluster's old age is well established from stellar populations.",
        unresolved_ambiguity="Rules out core collapse for THIS source only. Whether it represents a rare channel or a substantial fraction of the population is unknown.",
    ),
    dict(
        evidence_id="EV-H08",
        observation="Same globular-cluster localization read as positive evidence for compact-object formation channels available to old populations (accretion-induced collapse of a white dwarf, WD-WD or NS-WD merger products, dynamically assembled binaries).",
        source_name="FRB 20200120E",
        citation="Kirsten et al. 2022, Nature",
        locator="abstract and discussion of formation channels",
        hypothesis="magnetar-alternative-channel (AIC / merger / dynamical assembly)",
        effect="supports",
        strength="strong",
        applies_to="single-source",
        confidence_note="The environment strongly constrains the formation channel; the specific channel among AIC / merger / dynamical capture is not determined.",
        unresolved_ambiguity="Globular clusters have high stellar interaction rates, so per-star rates there are not transferable to field populations; the channel could be strongly over-represented in clusters.",
    ),
    dict(
        evidence_id="EV-H09",
        observation="FRB 20200120E has a very low dispersion measure (~88 pc cm^-3 total), leaving little room for a dense magnetized local nebula along the line of sight.",
        source_name="FRB 20200120E",
        citation="Bhardwaj et al. 2021, ApJL",
        locator="abstract; DM budget and M81 association",
        hypothesis="all FRB sources sit inside dense young nebulae (as inferred for FRB 121102)",
        effect="challenges",
        strength="moderate",
        applies_to="single-source",
        confidence_note="DM value is well measured; the DM budget decomposition into Milky Way, halo, host and local contributions carries modelling uncertainty.",
        unresolved_ambiguity="A low integrated DM does not exclude a compact, low-filling-factor magnetized region very close to the source.",
    ),
    dict(
        evidence_id="EV-H10",
        observation="Galactic magnetar SGR 1935+2154 emitted an FRB-like millisecond radio burst (fluence of order 1 MJy ms) simultaneously with a hard X-ray burst.",
        source_name="SGR 1935+2154 (Galactic magnetar)",
        citation="CHIME/FRB Collaboration 2020, Nature; Bochenek et al. 2020, Nature",
        locator="abstracts; burst detection and fluence",
        hypothesis="magnetar (any formation channel) as an FRB engine",
        effect="supports",
        strength="strong",
        applies_to="all",
        confidence_note="Detection by two independent instruments; magnetar identification unambiguous. Establishes existence, not dominance, of a magnetar channel.",
        unresolved_ambiguity="Shows magnetars CAN make FRB-like bursts; does not show that the cosmological FRB population is made this way.",
    ),
    dict(
        evidence_id="EV-H11",
        observation="Isotropic-equivalent radio energy of the SGR 1935+2154 burst is ~1e34-3e35 erg (distance-dependent), roughly 4-5 orders of magnitude below a typical cosmological FRB and ~7 dex below the brightest localized events.",
        source_name="SGR 1935+2154 (Galactic magnetar); cosmological FRB comparison set",
        citation="artifact:frb_energetics_scaling.py and artifact:frb_energetics_scaling_out.txt - unit conversion of published fluences to isotropic energy",
        locator="frb_energetics_scaling_out.txt, ratio block",
        hypothesis="magnetars like SGR 1935+2154 as the sole engine of cosmological FRBs",
        effect="challenges",
        strength="moderate",
        applies_to="all",
        confidence_note="Conversion is arithmetic, not a measurement; distance to SGR 1935+2154 is uncertain by ~factor 3 (about 1 dex in energy), and E_iso scales linearly with the assumed bandwidth.",
        unresolved_ambiguity="Unknown whether the energy gap is a continuous luminosity function extending over 7 dex or evidence for physically distinct populations; selection effects truncate the faint end.",
    ),
    dict(
        evidence_id="EV-H12",
        observation="Bursts from FRB 20200120E in the M81 globular cluster have isotropic energies overlapping the Galactic magnetar burst range, bridging part of the Galactic/extragalactic energy gap.",
        source_name="FRB 20200120E",
        citation="artifact:frb_energetics_scaling_out.txt - representative 1 Jy ms burst at 3.6 Mpc gives ~1.6e34 erg, below the 9 kpc SGR 1935+2154 value",
        locator="frb_energetics_scaling_out.txt, case table row 4",
        hypothesis="a single continuous FRB luminosity function spanning Galactic to cosmological energies",
        effect="supports",
        strength="weak",
        applies_to="repeaters",
        confidence_note="Uses a representative rather than a measured fluence for FRB 20200120E; treat as an order-of-magnitude framing only, not as a published energy.",
        unresolved_ambiguity="Overlap in energy does not imply a shared mechanism; a nearby low-energy repeater in an old cluster may belong to a different channel entirely.",
    ),
    dict(
        evidence_id="EV-H13",
        observation="FRB host galaxies span a wide range of stellar masses and star formation rates and are typically ordinary star-forming galaxies, not the extreme low-mass, low-metallicity systems that dominate SLSN and long-GRB host samples.",
        source_name="localized FRB host sample (multiple)",
        citation="Bhandari et al. 2020, ApJL; Heintz et al. 2020, ApJ",
        locator="abstracts; host demographic comparison to transient host samples",
        hypothesis="magnetar-core-collapse specifically via the SLSN/LGRB formation channel",
        effect="challenges",
        strength="moderate",
        applies_to="all",
        confidence_note="Conclusion rests on small samples (tens of hosts) with heterogeneous selection; statistical comparisons to transient host samples are sensitive to the comparison sample chosen.",
        unresolved_ambiguity="Whether FRB rate tracks stellar mass, star formation rate, or some mixture is unresolved; current samples cannot cleanly separate these.",
    ),
    dict(
        evidence_id="EV-H14",
        observation="Expanded ASKAP-era host sample confirms a mix of star-forming and low-specific-star-formation hosts with moderate stellar masses; no single host type dominates.",
        source_name="localized FRB host sample (ASKAP/CRAFT and others)",
        citation="Bhandari et al. 2022, AJ",
        locator="abstract; host property tables and comparison figures",
        hypothesis="a single young-progenitor channel producing all FRBs",
        effect="challenges",
        strength="moderate",
        applies_to="all",
        confidence_note="Selection favours bright, low-redshift, well-imaged hosts; unbiased demographics are not yet available.",
        unresolved_ambiguity="Host diversity is consistent both with several progenitor channels and with one channel having a broad delay-time distribution.",
    ),
    dict(
        evidence_id="EV-H15",
        observation="FRB 180924 localized to a massive galaxy with low specific star formation rate, offset several kiloparsecs from the galaxy centre; no star-forming knot at the burst position.",
        source_name="FRB 20180924B",
        citation="Bannister et al. 2019, Science",
        locator="abstract; host identification and offset measurement",
        hypothesis="magnetar-core-collapse with a young magnetar",
        effect="challenges",
        strength="moderate",
        applies_to="non-repeaters",
        confidence_note="Localization is secure; the inference of an old progenitor from the integrated host colours is model-dependent.",
        unresolved_ambiguity="Low-level, spatially localized star formation below the imaging limit cannot be excluded at the burst position.",
    ),
    dict(
        evidence_id="EV-H16",
        observation="FRB 190523 localized to a massive galaxy with a low star formation rate, unlike the dwarf host of FRB 121102.",
        source_name="FRB 20190523A",
        citation="Ravi et al. 2019, Nature",
        locator="abstract; host association and stellar population discussion",
        hypothesis="magnetar-core-collapse with a young magnetar",
        effect="challenges",
        strength="moderate",
        applies_to="non-repeaters",
        confidence_note="Localization region is larger than for VLBI-localized sources; host association is probabilistic rather than definitive.",
        unresolved_ambiguity="Single source; does not exclude a young magnetar formed in a low-luminosity star-forming pocket within the massive host.",
    ),
    dict(
        evidence_id="EV-H17",
        observation="Projected host-centric offsets of localized FRBs, from HST imaging, mostly fall within the host stellar light at a few kiloparsecs, tracking the light distribution more closely than short-GRB offsets but less tightly than core-collapse SNe.",
        source_name="localized FRB host sample (HST imaging)",
        citation="Mannings et al. 2021, ApJ",
        locator="abstract; offset distribution and comparison to transient classes",
        hypothesis="compact-object merger (NS-NS / NS-BH) as the dominant FRB channel",
        effect="challenges",
        strength="moderate",
        applies_to="all",
        confidence_note="Small sample (order ten hosts) and projected (not physical) offsets; the comparison-class offset distributions themselves carry uncertainty.",
        unresolved_ambiguity="Intermediate offsets are also produced by kicked neutron stars from core collapse, so the offset distribution alone does not separate the channels.",
    ),
    dict(
        evidence_id="EV-H18",
        observation="Persistent radio sources are rare: only two secure PRS associations (FRB 121102 and FRB 20190520B) among several tens of well-localized FRBs.",
        source_name="localized FRB sample",
        citation="Chatterjee et al. 2017, Nature; Niu et al. 2022, Nature",
        locator="abstracts of both, read together with the absence of comparable detections elsewhere",
        hypothesis="all FRB sources are embedded in luminous young magnetized nebulae",
        effect="challenges",
        strength="moderate",
        applies_to="all",
        confidence_note="The non-detections are heterogeneous in depth and mostly not published as a uniform limit set; this row is a statement about the published record, not a rate measurement.",
        unresolved_ambiguity="PRS rarity may reflect source age (nebulae fade) rather than distinct progenitors. A uniform limit compilation is needed; see the open task frb-task-prs-incidence.",
    ),
    dict(
        evidence_id="EV-H19",
        observation="FRB 20220610A localized to z=1.016, the most distant well-localized FRB at the time of publication, in a morphologically complex, apparently interacting galaxy system.",
        source_name="FRB 20220610A",
        citation="Ryder et al. 2023, Science",
        locator="abstract; redshift determination and host imaging",
        hypothesis="progenitors form in star-forming systems and exist out to z~1",
        effect="supports",
        strength="moderate",
        applies_to="non-repeaters",
        confidence_note="Redshift is spectroscopic and secure; the interacting/compact-group interpretation of the host morphology is less certain.",
        unresolved_ambiguity="Whether the host is a single disturbed galaxy or a group affects host DM and stellar-mass estimates, and hence the inferred environment.",
    ),
    dict(
        evidence_id="EV-H20",
        observation="Implied isotropic energy of FRB 20220610A is of order 1e42 erg under standard bandwidth assumptions, near the top of the observed FRB energy distribution.",
        source_name="FRB 20220610A",
        citation="artifact:frb_energetics_scaling_out.txt - 45 Jy ms at z=1.016 gives 1.28e42 erg for a 1 GHz bandwidth",
        locator="frb_energetics_scaling_out.txt, case table final row",
        hypothesis="energetic ceiling of magnetar-powered emission models",
        effect="challenges",
        strength="weak",
        applies_to="single-source",
        confidence_note="The input fluence (45 Jy ms) is approximate and should be VERIFIED against Ryder et al. 2023; the energy scales linearly with the assumed bandwidth.",
        unresolved_ambiguity="Magnetar magnetic energy reservoirs plausibly reach 1e47-1e49 erg, so a 1e42 erg burst is not obviously prohibitive; the constraint bites only through the radio efficiency, which is unknown.",
    ),
    dict(
        evidence_id="EV-H21",
        observation="Dispersion measures of localized FRBs follow the expected DM-redshift (Macquart) relation, confirming that most of the DM is intergalactic and accounting for the cosmic baryon content.",
        source_name="localized FRB sample",
        citation="Macquart et al. 2020, Nature",
        locator="abstract; DM-z relation fit",
        hypothesis="all progenitor hypotheses (consistency check, not a discriminant)",
        effect="neutral",
        strength="strong",
        applies_to="all",
        confidence_note="Result is robust for the sample used but rests on a small number of localizations and on an assumed cosmic baryon distribution model.",
        unresolved_ambiguity="Scatter in the relation absorbs host plus local DM contributions, so individual local-environment densities remain poorly constrained by this method.",
    ),
    dict(
        evidence_id="EV-H22",
        observation="Host plus local DM contributions inferred from the Macquart relation are typically modest (order 100 pc cm^-3 or less in the rest frame) for most localized FRBs.",
        source_name="localized FRB sample",
        citation="Macquart et al. 2020, Nature",
        locator="abstract and DM budget discussion; inference by this contributor from the fit residuals",
        hypothesis="FRB sources generically sit in dense young supernova remnants or magnetar nebulae",
        effect="challenges",
        strength="weak",
        applies_to="all",
        confidence_note="This is a downstream inference by this contributor, not a stated result of the paper; the host DM inference is degenerate with the assumed IGM model and is weakened by small samples.",
        unresolved_ambiguity="A young dense remnant contributes strongly to DM for only a few hundred years, so a modest host DM may indicate age rather than a different progenitor.",
    ),
    dict(
        evidence_id="EV-H23",
        observation="CHIME/FRB Catalog 1 reports 536 FRBs including 62 bursts from 18 repeating sources, and an inferred sky rate of roughly 800 events per sky per day above about 5 Jy ms at 400-800 MHz.",
        source_name="CHIME/FRB Catalog 1 sample",
        citation="CHIME/FRB Collaboration 2021, ApJS",
        locator="abstract; population and rate sections",
        hypothesis="cataclysmic one-off channels (compact-object mergers) as the dominant FRB source",
        effect="challenges",
        strength="moderate",
        applies_to="all",
        confidence_note="The sky rate is well measured for CHIME's band and selection function; converting it to a volumetric rate for comparison with merger rates requires an assumed luminosity function and redshift distribution.",
        unresolved_ambiguity="The rate argument can be evaded by strong beaming or by a luminosity function with many faint events; it constrains but does not exclude cataclysmic channels.",
    ),
    dict(
        evidence_id="EV-H24",
        observation="The observed repeater fraction in CHIME/FRB Catalog 1 is small (order a few percent of sources) but is consistent with a scenario in which all sources repeat at low rates, given the finite exposure.",
        source_name="CHIME/FRB Catalog 1 sample",
        citation="CHIME/FRB Collaboration 2021, ApJS",
        locator="abstract; repeater statistics section",
        hypothesis="all FRBs repeat (single population)",
        effect="neutral",
        strength="moderate",
        applies_to="all",
        confidence_note="Exposure-limited. The measured fraction is a lower limit on the true repeating fraction, not an estimate of it.",
        unresolved_ambiguity="Fundamental degeneracy between a broad repetition-rate distribution in one population and two genuinely distinct populations; see frb-open-question-all-repeat.",
    ),
    dict(
        evidence_id="EV-H25",
        observation="Bursts from repeaters are on average temporally broader and spectrally narrower (more band-limited) than bursts from apparent non-repeaters in the CHIME sample.",
        source_name="CHIME/FRB Catalog 1 sample",
        citation="Pleunis et al. 2021, ApJ",
        locator="abstract; morphological classification and comparison of the two samples",
        hypothesis="all FRBs repeat (single population with identical emission physics)",
        effect="challenges",
        strength="moderate",
        applies_to="all",
        confidence_note="The morphological difference is statistically significant in the CHIME sample but is sensitive to instrumental selection on bandwidth and duration.",
        unresolved_ambiguity="A morphological difference can arise from viewing geometry, beaming, or propagation within a single population; it does not by itself require two progenitor classes.",
    ),
]


def main():
    out = sys.argv[1]
    with open(out, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=COLUMNS, quoting=csv.QUOTE_MINIMAL)
        w.writeheader()
        for r in ROWS:
            assert set(r) == set(COLUMNS), sorted(set(r) ^ set(COLUMNS))
            w.writerow(r)
    print("wrote %d rows to %s" % (len(ROWS), out))


if __name__ == "__main__":
    main()
